image:
  registry: docker.io
  repository: bitnami/flink
  tag: 1.20.0-debian-12-r9
  pullPolicy: IfNotPresent

jobmanager:
  replicaCount: 1
  resourcesPreset: "small"
  containerPorts:
    rpc: 6123
    http: 8081
    blob: 6124
  service:
    type: ClusterIP
    ports:
      rpc: 6123
      http: 8081
      blob: 6124

taskmanager:
  replicaCount: 1
  resourcesPreset: "small"
  containerPorts:
    data: 6121
    rpc: 6122
  service:
    type: ClusterIP
    ports:
      data: 6121
      rpc: 6122